---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install atlasswprobe packages.
  package:
    name: atlasswprobe
    state: present

- name: Enable atlas service.
  service:
    name: atlas
    state: "{{ atlas_state }}"
    enabled: "{{ atlas_enabled }}"
